### ISSUE TITLE
Average charging power calculation

### ISSUE THREAD

**Issue by jumpjack** [hacf-fr/renault-api#567] opened 2022-03-21 13:50 UTC
My Zoe50 does not return charging power data, but maybe the average power could be added to the output, given that duration and charged kWh are returned by **/charge-history**:

**/charge-history**
```
        {
            "day": "20220317",
            "totalChargesNumber": 1,
            "totalChargesEnergyRecovered": 5.4,
            "totalChargesDuration": 241
        },
```

**/charges:**
```
        {
            "chargeStartDate": "2022-03-17T01:01:10Z",
            "chargeEndDate": "2022-03-17T05:02:01Z",
            "chargeDuration": 14451,
            "chargeEndBatteryLevel": 74,
            "chargeEndStatus": "error"
        },
```

Beware of different unit of measure in **/charge-history** (minutes) and **/charge** (seconds).

**Comment by oliv3r** [comment] 2024-06-04 11:26
I haven't figured out yet why, but my ZOE40 stopped reporting the charge power since last week. The original app also doesn't know; so this may be more interesting anyway...

**Comment by oliv3r** [comment] 2024-06-14 05:19
@epenet that's what the car API knows, right? regardless, you'd have to know valid timestamps no? There's no 'now()' or 'now()' and 'previous()' so you'd have to do quite a bit of math.

Obviously this would be a hass change only; but the idea would be that when you get the current measurant, you also get the one 'just before' it (or remember your previous one) and calculate the average charge power over that interval. But so far I haven't heard anybody else stating they have lost this information like I have here https://github.com/hacf-fr/renault-api/issues/1213 so that makes me wonder if the car simply stopped reporting it; and the TCU is using an older version of the firmware.

**Comment by epenet** [comment] 2024-06-14 05:25
The Renault API has been all over the place these past few months.
Endpoints keep changing one way, and then another way.
Even the official phone app can't keep up - with data disappearing and reappearing.

I will still happily take PRs for Home Assistant and for this project

**Comment by oliv3r** [comment] 2024-06-14 08:48
@epenet did you not also have an ZE40? I'm just surprised I'm the only one suffering from these changes :p

**Comment by epenet** [comment] 2024-06-14 08:52
Yes I have a Zoe40, and I suffer also from these changes - but that doesn't mean that I am responsible for the dodgy API from Renault that keeps changing and breaking.

**Comment by oliv3r** [comment] 2024-06-14 09:14
> Yes I have a Zoe40, and I suffer also from these changes - but that doesn't mean that I am responsible for the dodgy API from Renault that keeps changing and breaking.

Haha, no that's not what I meant, but it IS confirmation that the issue is not just mine :) Thanks for confirming :)

**Comment by epenet** [comment] 2024-06-28 09:53
Closing this - feel free to open a PR

**Closed by epenet** 2024-06-28 09:53 UTC
