### ISSUE TITLE
JSON option not working?

### ISSUE THREAD

**Issue by wivaku** [hacf-fr/renault-api#467] opened 2022-01-10 12:46 UTC
I tried: `renault-api --json status`

```
----------------  -------------------
Total mileage     xxx.xx km
GPS Latitude      xxx
GPS Longitude     xxx
GPS last updated  2022-01-10 13:36:19
HVAC status       off
----------------  -------------------
```

Was expecting JSON output
(and -for my Dacia Spring EV car-: was hoping for more output, especially charge status)

**Comment by usky73** [comment] 2022-01-16 07:52
same for me

**Comment by epenet** [comment] 2022-01-27 19:36
The JSON output doesn't apply to the "status" command.
The status command talks to multiple endpoints, and formats the result automatically.

If you wish to return JSON, you should query the endpoints individually:
```console
renault-api --json http get "/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v2/cars/{vin}/battery-status"
renault-api --json http get "/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v1/cars/{vin}/charge-mode"
renault-api --json http get "/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v2/cars/{vin}/cockpit"
renault-api --json http get "/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v1/cars/{vin}/location"
renault-api --json http get "/commerce/v1/accounts/{account_id}/kamereon/kca/car-adapter/v1/cars/{vin}/hvac-status"
```

**Comment by epenet** [comment] 2022-01-27 19:36
We also have this PR open regarding the support for Dacia Spring: #459

**Comment by epenet** [comment] 2022-01-27 19:59
Note: this is a duplicate of #188

**Closed by epenet** 2022-01-27 19:59 UTC
